name: Laravel Dusk

on:
  push:
    branches: [ 2.0 ]
  pull_request:
    branches: [ 2.0 ]

jobs:
  dusk:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        laravel: [ "11.*", "12.*" ]
        php: [ "8.3" ]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -p123456"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer:v2
          extensions: mbstring, pdo_mysql, zip
          coverage: none

      - name: Install Dependencies
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-tests "${{ matrix.laravel }}"
          sh ./tests/bin/install-dep.sh

      - name: Install Admin
        run: sh ./tests/bin/install-admin.sh

      - name: Start Server
        run: sh ./tests/bin/start.sh

      - name: Run test suite
        run: cd ./laravel-tests && php artisan dusk --without-tty
